// Code generated by go-swagger; DO NOT EDIT.

// Package restserver Hospital server
//
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /api/hospital/v2
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: DreamSO<dreamsocom@gmail.com> http://wso2.com/products/api-manager/
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - text/plain
//
// swagger:meta
package restserver
